"""empty message

Revision ID: 23414e1df2cb
Revises: d062fe5d39f7
Create Date: 2017-03-14 04:14:51.686252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23414e1df2cb'
down_revision = 'd062fe5d39f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('userid', sa.Integer(), nullable=True))
    op.add_column('user_profile', sa.Column('username', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['userid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'username')
    op.drop_column('user_profile', 'userid')
    # ### end Alembic commands ###
