"""empty message

Revision ID: d062fe5d39f7
Revises: 0df720464645
Create Date: 2017-03-12 22:34:04.760614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd062fe5d39f7'
down_revision = '0df720464645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'user_profile_userid_key', 'user_profile', type_='unique')
    op.drop_column('user_profile', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('userid', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'user_profile_userid_key', 'user_profile', ['userid'])
    # ### end Alembic commands ###
